# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: qna_development
  pool: 5
  timeout: 5000
  username: root
  password: 'qwerty123'

test:
  adapter: postgresql
  encoding: unicode
  database: qna_test
  pool: 5
  timeout: 5000
  username: root
  password: 'qwerty123'